services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadmus-challenge
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cadmusdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwe123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - cadmus-challenge-network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: cadmusdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cadmus-challenge-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8000:80"
    networks:
      - cadmus-challenge-network
    depends_on:
      - db

networks:
  cadmus-challenge-network:

volumes:
  postgres-data:
